Repository bbta3-bppt/aeromit, pull requests merged in 2020-12, with the labels that each got.

#27 kelola awal lihat data user
  src/kegiatan/helpers.rs
  src/pengguna/dto.rs
  src/pengguna/handlers.rs
  src/pengguna/helpers.rs
  src/pengguna/mod.rs
  src/pengguna/models.rs
  src/pengguna/routes.rs
  src/pengguna/services/create_user.rs
  src/pengguna/services/get_users.rs
  src/pengguna/services/mod.rs
Labels: documentation, maintenance

#28 ralat author
  Cargo.toml
Labels: maintenance

#29 baca data pengguna tertentu
  src/pengguna/handlers.rs
  src/pengguna/routes.rs
  src/pengguna/services/get_user.rs
  src/pengguna/services/mod.rs
Labels: maintenance

#30 atur ulang module handler pengguna kedalam dir based
  Cargo.lock
  Cargo.toml
  src/pengguna/handlers.rs
  src/pengguna/handlers/create_user.rs
  src/pengguna/handlers/get_user.rs
  src/pengguna/handlers/get_users.rs
  src/pengguna/handlers/mod.rs
  src/pengguna/routes.rs
Labels: maintenance

#31 coba enkripsi password dan update readme
  Cargo.lock
  Cargo.toml
  README.md
  src/app/errors.rs
  src/pengguna/helpers.rs
  src/pengguna/services/create_user.rs
Labels: documentation, maintenance

#32 perbaikan return type trait dan bump up version
  Cargo.lock
  Cargo.toml
  src/pengguna/helpers.rs
Labels: maintenance

#34 kelola last modified untuk document
  src/app/helpers.rs
  src/app/mod.rs
  src/kegiatan/helpers.rs
  src/kegiatan/models.rs
  src/pengguna/helpers.rs
Labels: maintenance

#36 kelola aktif pengguna
  src/pengguna/dto.rs
  src/pengguna/handlers/delete_user.rs
  src/pengguna/handlers/get_user.rs
  src/pengguna/handlers/update_user.rs
  src/pengguna/helpers.rs
  src/pengguna/models.rs
  src/pengguna/services/create_user.rs
  src/pengguna/services/get_users.rs
Labels: maintenance

#38 koreksi minor dokumentasi
  src/pengguna/helpers.rs
Labels: documentation

#39 kelola awal pengguna untuk login
  src/pengguna/dto.rs
  src/pengguna/handlers/login_user.rs
  src/pengguna/handlers/mod.rs
  src/pengguna/helpers.rs
  src/pengguna/routes.rs
  src/pengguna/services/get_user.rs
  src/pengguna/services/get_users.rs
  src/pengguna/services/login_user.rs
  src/pengguna/services/mod.rs
Labels: maintenance

#40 update readme dan kelola awal token
  Cargo.lock
  Cargo.toml
  README.md
  src/app/errors.rs
  src/pengguna/handlers/login_user.rs
  src/pengguna/models.rs
  src/pengguna/services/login_user.rs
Labels: documentation, maintenance

#41 kelola lanjut login pengguna
  Cargo.lock
  Cargo.toml
  README.md
  src/app/errors.rs
  src/app/middlewares.rs
  src/app/mod.rs
  src/main.rs
  src/pengguna/handlers/login_user.rs
  src/pengguna/services/login_user.rs
Labels: documentation, maintenance

#42 kelola ulang routes dan penyesuaian handler
  src/pengguna/handlers/create_user.rs
  src/pengguna/handlers/delete_user.rs
  src/pengguna/handlers/get_user.rs
  src/pengguna/handlers/get_users.rs
  src/pengguna/handlers/update_user.rs
  src/pengguna/models.rs
  src/pengguna/routes.rs
  src/pengguna/services/login_user.rs
Labels: maintenance

#43 kelola ulang app dto dengan terapan impl
  src/app/dto.rs
  src/app/errors.rs
  src/app/handlers.rs
  src/kegiatan/handlers.rs
  src/pengguna/handlers/create_user.rs
  src/pengguna/handlers/delete_user.rs
  src/pengguna/handlers/get_user.rs
  src/pengguna/handlers/get_users.rs
  src/pengguna/handlers/login_user.rs
  src/pengguna/handlers/update_user.rs
Labels: maintenance

#44 Kelola lanjutan hak akses pengguna
  src/app/errors.rs
  src/app/mod.rs
  src/app/permissions/is_admin.rs
  src/app/permissions/is_authenticated.rs
  src/app/permissions/mod.rs
  src/kegiatan/handlers.rs
  src/pengguna/handlers/create_user.rs
  src/pengguna/handlers/delete_user.rs
  src/pengguna/handlers/get_user.rs
  src/pengguna/handlers/get_users.rs
  src/pengguna/handlers/update_user.rs
  src/pengguna/mod.rs
  src/pengguna/models.rs
  src/pengguna/services/login_user.rs
Labels: documentation, maintenance

#45 terapan perizinan terhadap kelola kegiatan
  src/kegiatan/handlers.rs
Labels: maintenance

#46 kelola tautan video untuk kegiatan
  Cargo.lock
  Cargo.toml
  src/app/helpers.rs
  src/kegiatan/dto.rs
  src/kegiatan/helpers.rs
  src/kegiatan/models.rs
Labels: maintenance

#47 kelola awal ui
  .gitignore
  README.md
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/pages/_app.js
  src_ui/pages/index.js
  src_ui/public/favicon.ico
  src_ui/public/vercel.svg
  src_ui/styles/Home.module.css
  src_ui/styles/globals.css
Labels: maintenance

#48 kelola lanjut struktur ui
  src_ui/components/topbar.js
  src_ui/layouts/default.js
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/pages/_app.js
  src_ui/pages/index.js
  src_ui/styles/Home.module.css
  src_ui/styles/base.css
  src_ui/styles/color.js
  src_ui/styles/globals.css
Labels: maintenance

#49 kelola proses logout pengguna
  Cargo.lock
  Cargo.toml
  src/pengguna/handlers/logout_user.rs
  src/pengguna/handlers/mod.rs
  src/pengguna/routes.rs
  src/pengguna/services/logout_user.rs
  src/pengguna/services/mod.rs
Labels: maintenance

#50 kelola komponen modal info
  src_ui/components/modals/info.js
  src_ui/components/topbar.js
  src_ui/layouts/default.js
  src_ui/pages/index.js
  src_ui/public/favicon.ico
Labels: maintenance

#51 kelola menu pengaturan dan container
  src_ui/components/menu/topbar_settings.js
  src_ui/components/modals/info.js
  src_ui/components/modals/topbar_info.js
  src_ui/components/topbar.js
Labels: maintenance

#52 perbaikan fungsi update kegiatan
  Cargo.lock
  Cargo.toml
  src/kegiatan/dto.rs
  src/kegiatan/helpers.rs
  src/kegiatan/models.rs
Labels: maintenance

#53 kelola cek session dan koreksi minor dokumentasi
  Cargo.lock
  Cargo.toml
  src/pengguna/handlers/check_user.rs
  src/pengguna/handlers/delete_user.rs
  src/pengguna/handlers/get_user.rs
  src/pengguna/handlers/mod.rs
  src/pengguna/handlers/update_user.rs
  src/pengguna/routes.rs
  src/pengguna/services/check_user.rs
  src/pengguna/services/mod.rs
Labels: documentation, maintenance

#54 membuat halaman awal profil dan login
  src_ui/components/menu/topbar_settings.js
  src_ui/pages/masuk.js
  src_ui/pages/profil.js
Labels: maintenance

#55 perombakan komponen, layout dan dokumentasi dialog
  README.md
  src_ui/.editorconfig
  src_ui/.eslintignore
  src_ui/.eslintrc.js
  src_ui/.gitignore
  src_ui/.postcssrc.js
  src_ui/.vscode/extensions.json
  src_ui/.vscode/settings.json
  src_ui/README.md
  src_ui/babel.config.js
  src_ui/components/menu/topbar_settings.js
  src_ui/components/modals/topbar_info.js
  src_ui/components/topbar.js
  src_ui/jsconfig.json
  src_ui/layouts/default.js
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/pages/_app.js
  src_ui/pages/index.js
  src_ui/pages/masuk.js
  src_ui/pages/profil.js
  src_ui/public/favicon.ico
  src_ui/public/icons/favicon-128x128.png
  src_ui/public/icons/favicon-16x16.png
  src_ui/public/icons/favicon-32x32.png
  src_ui/public/icons/favicon-96x96.png
  src_ui/public/vercel.svg
  src_ui/quasar.conf.js
  src_ui/src/App.vue
  src_ui/src/assets/.gitkeep
  src_ui/src/boot/.gitkeep
  src_ui/src/boot/axios.js
  src_ui/src/components/.gitkeep
  src_ui/src/components/layouts/InfoDialog.vue
  src_ui/src/css/app.sass
  src_ui/src/css/base/_typography.sass
  src_ui/src/css/quasar.variables.sass
  src_ui/src/handlers/components/dialog/index.js
  src_ui/src/handlers/layouts/index.js
  src_ui/src/index.template.html
  src_ui/src/layouts/MainLayout.vue
  src_ui/src/pages/Error404.vue
  src_ui/src/pages/Index.vue
  src_ui/src/router/index.js
  src_ui/src/router/routes.js
  src_ui/src/store/index.js
  src_ui/src/store/layouts/actions.js
  src_ui/src/store/layouts/getters.js
  src_ui/src/store/layouts/index.js
  src_ui/src/store/layouts/mutations.js
  src_ui/src/store/layouts/state.js
  src_ui/src/store/store-flag.d.ts
  src_ui/styles/base.css
  src_ui/styles/color.js
Labels: documentation, maintenance

#56 menambahkan field banyak pembicara kedalam database
  Cargo.lock
  Cargo.toml
  src/app/helpers.rs
  src/kegiatan/dto.rs
  src/kegiatan/handlers.rs
  src/kegiatan/helpers.rs
  src/kegiatan/models.rs
  src/kegiatan/services.rs
  src_ui/package.json
  src_ui/src/components/layouts/InfoDialog.vue
  src_ui/src/components/layouts/MenuSettings.vue
  src_ui/src/handlers/components/menu/index.js
  src_ui/src/layouts/MainLayout.vue
  src_ui/src/pages/Login.vue
  src_ui/src/pages/Profil.vue
  src_ui/src/router/routes.js
Labels: maintenance

#57 kelola field tags dan penyesuaian terapan fungsi helper
  src/app/helpers.rs
  src/kegiatan/dto.rs
  src/kegiatan/helpers.rs
  src/kegiatan/models.rs
Labels: maintenance

#58 modifikasi halaman utama dengan kartu kegiatan
  src_ui/package.json
  src_ui/src/components/pages/ActivityCard.vue
  src_ui/src/css/app.sass
  src_ui/src/css/base/_layout.sass
  src_ui/src/layouts/MainLayout.vue
  src_ui/src/pages/Index.vue
Labels: maintenance

#59 Render data kegiatan dari database
  Cargo.lock
  Cargo.toml
  src/app/middlewares.rs
  src/main.rs
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/quasar.conf.js
  src_ui/src/components/pages/ActivityCard.vue
  src_ui/src/handlers/pages/utama.js
  src_ui/src/pages/Index.vue
  src_ui/src/store/index.js
  src_ui/src/store/kegiatan/actions.js
  src_ui/src/store/kegiatan/getters.js
  src_ui/src/store/kegiatan/index.js
  src_ui/src/store/kegiatan/mutations.js
  src_ui/src/store/kegiatan/state.js
Labels: maintenance

#60 membuat rincian kegiatan melalui dialog
  src_ui/src/components/pages/ActivityCard.vue
  src_ui/src/handlers/pages/utama.js
  src_ui/src/pages/Index.vue
  src_ui/src/store/kegiatan/getters.js
  src_ui/src/store/kegiatan/mutations.js
  src_ui/src/store/kegiatan/state.js
Labels: enhancement, maintenance

#61 modifikasi error handling dan menampilkan error banner
  Cargo.lock
  Cargo.toml
  src/app/errors.rs
  src/app/permissions/is_authenticated.rs
  src_ui/package.json
  src_ui/src/components/pages/ActivityCard.vue
  src_ui/src/css/base/_layout.sass
  src_ui/src/pages/Index.vue
Labels: maintenance

#62 pemisahan template dan script serta halaman login
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/quasar.conf.js
  src_ui/src/css/base/_layout.sass
  src_ui/src/handlers/components/menu/index.js
  src_ui/src/handlers/pages/masuk.js
  src_ui/src/handlers/pages/utama.js
  src_ui/src/pages/Index.vue
  src_ui/src/pages/Login.vue
Labels: maintenance

#63 pemisahan template dan script masing-masing komponen dan layout
  src_ui/src/components/layouts/InfoDialog.vue
  src_ui/src/components/layouts/MenuSettings.vue
  src_ui/src/components/pages/ActivityCard.vue
  src_ui/src/handlers/components/card/ActivityCard.js
  src_ui/src/handlers/components/dialog/InfoDialog.js
  src_ui/src/handlers/components/menu/MenuSettings.js
  src_ui/src/handlers/layouts/MainLayout.js
  src_ui/src/layouts/MainLayout.vue
Labels: maintenance

#64 Merge pull request #27 from bbta3-bppt/main
  src_ui/src/components/ActivityCard/ActivityCard.js
  src_ui/src/components/ActivityCard/ActivityCard.vue
  src_ui/src/components/InfoDialog/InfoDialog.js
  src_ui/src/components/InfoDialog/InfoDialog.vue
  src_ui/src/components/MenuSettings/MenuSettings.js
  src_ui/src/components/MenuSettings/MenuSettings.vue
  src_ui/src/handlers/dialog.js
  src_ui/src/handlers/layout.js
  src_ui/src/handlers/menu.js
  src_ui/src/layouts/MainLayout/MainLayout.js
  src_ui/src/layouts/MainLayout/MainLayout.vue
  src_ui/src/pages/Login/Login.vue
  src_ui/src/pages/Login/login.js
  src_ui/src/pages/Utama/Utama.vue
  src_ui/src/pages/Utama/utama.js
  src_ui/src/router/routes.js
Labels: maintenance
