Repository bbta3-bppt/aeromit, pull requests merged in 2020-11, with the labels that each got.

#1 tambah crates untuk database
  Cargo.lock
  Cargo.toml
Labels: dependencies, maintenance

#2 Kelola ulang routes dan middleware
  README.md
  src/app/handlers.rs
  src/app/mod.rs
  src/app/routes.rs
  src/main.rs
Labels: dependencies, documentation, maintenance

#3 Terapan data transfer object app
  src/app/dto.rs
  src/app/handlers.rs
  src/app/mod.rs
  src/app/routes.rs
Labels: maintenance

#5 Membantu tambah dokumentasi
  README.md
  src/app/dto.rs
  src/app/mod.rs
  src/app/routes.rs
Labels: documentation

#6 Tambah dan perbarui dokumen module app handler
  README.md
  src/app/handlers.rs
  src/app/routes.rs
Labels: documentation

#7 Lanjutan dokumentasi kegiatan
  src/app/routes.rs
  src/kegiatan/handlers.rs
  src/kegiatan/mod.rs
  src/kegiatan/routes.rs
Labels: documentation

#8 Membuat koneksi awal database
  Cargo.lock
  Cargo.toml
  src/kegiatan/handlers.rs
  src/main.rs
Labels: maintenance

#9 Pergerakan awal dengan koneksi database
  Cargo.lock
  Cargo.toml
  README.md
  src/kegiatan/handlers.rs
  src/kegiatan/mod.rs
  src/kegiatan/models.rs
  src/main.rs
Labels: documentation, maintenance

#10 Penyesuaian service baca kegiatan
  src/kegiatan/handlers.rs
  src/kegiatan/mod.rs
  src/kegiatan/services.rs
Labels: maintenance

#11 Bump up version dan kelola awal error handling
  Cargo.lock
  Cargo.toml
  src/app/errors.rs
  src/app/mod.rs
  src/kegiatan/handlers.rs
  src/kegiatan/helpers.rs
  src/kegiatan/mod.rs
  src/kegiatan/models.rs
  src/kegiatan/services.rs
  src/main.rs
Labels: dependencies, enhancement, maintenance

#12 Membuat module konfigurasi aplikasi
  src/app/configs.rs
  src/app/errors.rs
  src/app/mod.rs
  src/main.rs
Labels: maintenance

#13 Terapan lanjut error handling
  src/app/configs.rs
  src/app/errors.rs
  src/kegiatan/handlers.rs
  src/kegiatan/helpers.rs
  src/kegiatan/services.rs
Labels: maintenance

#14 Membuat fungsi init config
  src/app/configs.rs
  src/main.rs
Labels: maintenance

#17 Terapkan skip dan limit kedalam query document
  README.md
  src/kegiatan/dto.rs
  src/kegiatan/handlers.rs
  src/kegiatan/mod.rs
  src/kegiatan/services.rs
Labels: maintenance

#18 tambah fungsi lihat kegiatan tertentu
  src/app/errors.rs
  src/kegiatan/handlers.rs
  src/kegiatan/helpers.rs
  src/kegiatan/routes.rs
  src/kegiatan/services.rs
Labels: maintenance

#19 Kelola awal tambah kegiatan baru
  src/app/errors.rs
  src/kegiatan/dto.rs
  src/kegiatan/handlers.rs
  src/kegiatan/models.rs
  src/kegiatan/routes.rs
  src/kegiatan/services.rs
Labels: maintenance

#20 Penyesuaian fungsi tambah kegiatan
  src/kegiatan/handlers.rs
  src/kegiatan/services.rs
Labels: maintenance

#21 uji coba menggunakan markdown icon kedalam readme
  README.md
Labels: documentation

#22 Kelola dokumen kegiatan melalui ubah data
  src/kegiatan/handlers.rs
  src/kegiatan/helpers.rs
  src/kegiatan/routes.rs
  src/kegiatan/services.rs
Labels: maintenance

#23 hapus kegiatan dan koreksi mini dokumen
  Cargo.lock
  Cargo.toml
  src/kegiatan/handlers.rs
  src/kegiatan/routes.rs
  src/kegiatan/services.rs
Labels: documentation, maintenance

#24 pembuatan awal module pengguna
  src/kegiatan/mod.rs
  src/main.rs
  src/pengguna/mod.rs
  src/pengguna/models.rs
Labels: enhancement

#25 Terapan validasi input data transfer object untuk kegiatan
  Cargo.lock
  Cargo.toml
  src/app/errors.rs
  src/kegiatan/dto.rs
  src/kegiatan/services.rs
  src/pengguna/dto.rs
  src/pengguna/mod.rs
  src/pengguna/services/create_user.rs
  src/pengguna/services/mod.rs
Labels: maintenance
