Repository bbta3-bppt/aeromit, pull requests merged in 2021-01, with the labels that each got.

#65 Ganti model otentikasi menjadi stateless dan penyesuaian service handlers
  Cargo.lock
  Cargo.toml
  src/app/errors.rs
  src/app/helpers.rs
  src/app/middlewares.rs
  src/app/permissions/is_admin.rs
  src/app/permissions/is_authenticated.rs
  src/kegiatan/handlers.rs
  src/kegiatan/services.rs
  src/main.rs
  src/pengguna/handlers/check_user.rs
  src/pengguna/handlers/create_user.rs
  src/pengguna/handlers/delete_user.rs
  src/pengguna/handlers/get_user.rs
  src/pengguna/handlers/get_users.rs
  src/pengguna/handlers/login_user.rs
  src/pengguna/handlers/logout_user.rs
  src/pengguna/handlers/mod.rs
  src/pengguna/handlers/update_user.rs
  src/pengguna/routes.rs
  src/pengguna/services/check_user.rs
  src/pengguna/services/login_user.rs
  src/pengguna/services/logout_user.rs
  src/pengguna/services/mod.rs
  src_ui/package.json
Labels: enhancement

#67 Koreksi dokumentasi fungsi services
  src/kegiatan/services.rs
Labels: documentation

#68 melakukan penyesuaian proses hapus kegiatan
  Cargo.lock
  Cargo.toml
  src/kegiatan/dto.rs
  src/kegiatan/handlers.rs
  src/kegiatan/helpers.rs
  src/kegiatan/models.rs
  src/kegiatan/services.rs
  src_ui/package-lock.json
Labels: maintenance

#69 modifikasi lanjut crates dan token
  Cargo.lock
  Cargo.toml
  src/app/middlewares.rs
  src/main.rs
  src/pengguna/handlers/login_user.rs
  src/pengguna/services/login_user.rs
  src_ui/src/pages/Login/login.js
Labels: maintenance

#71 penyesuian ui dan perbaikan dokumentasi fungsi
  Cargo.lock
  Cargo.toml
  src/app/helpers.rs
  src/app/middlewares.rs
  src/app/permissions/is_admin.rs
  src/app/permissions/is_authenticated.rs
  src/kegiatan/handlers.rs
  src/main.rs
  src/pengguna/handlers/check_user.rs
  src/pengguna/handlers/create_user.rs
  src/pengguna/handlers/delete_user.rs
  src/pengguna/handlers/get_user.rs
  src/pengguna/handlers/get_users.rs
  src/pengguna/handlers/login_user.rs
  src/pengguna/handlers/update_user.rs
  src/pengguna/services/login_user.rs
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/src/components/ActivityCard/ActivityCard.vue
  src_ui/src/pages/Login/login.js
  src_ui/src/pages/Utama/utama.js
  src_ui/src/store/kegiatan/actions.js
Labels: maintenance

#72 Penambahan dokumentasi dan terapan env
  README.md
  src_ui/package.json
  src_ui/quasar.conf.js
  src_ui/src/components/ActivityCard/ActivityCard.vue
  src_ui/src/pages/Login/login.js
  src_ui/src/store/kegiatan/actions.js
Labels: documentation, maintenance

#73 modifikasi keseragaman tinggi card dan env ui
  README.md
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/quasar.conf.js
  src_ui/src/components/ActivityCard/ActivityCard.vue
Labels: maintenance

#74 koreksi cek status user dan terapan state masuk
  src/pengguna/services/check_user.rs
  src_ui/quasar.conf.js
  src_ui/src/boot/oten.js
  src_ui/src/components/MenuSettings/MenuSettings.vue
  src_ui/src/pages/Login/login.js
  src_ui/src/router/routes.js
  src_ui/src/store/index.js
  src_ui/src/store/otentikasi/actions.js
  src_ui/src/store/otentikasi/getters.js
  src_ui/src/store/otentikasi/index.js
  src_ui/src/store/otentikasi/mutations.js
  src_ui/src/store/otentikasi/state.js
Labels: maintenance

#75 Update UI README
  src_ui/README.md
Labels: documentation

#76 Kelola fungsi dan state untuk masuk
  src_ui/src/boot/oten.js
  src_ui/src/components/InfoDialog/InfoDialog.js
  src_ui/src/handlers/error.js
  src_ui/src/handlers/layout.js
  src_ui/src/handlers/menu.js
  src_ui/src/layouts/MainLayout/MainLayout.js
  src_ui/src/layouts/MainLayout/MainLayout.vue
  src_ui/src/pages/Login/Login.vue
  src_ui/src/pages/Login/login.js
  src_ui/src/pages/Utama/utama.js
  src_ui/src/router/routes.js
  src_ui/src/store/kegiatan/getters.js
  src_ui/src/store/kegiatan/state.js
  src_ui/src/store/otentikasi/actions.js
Labels: maintenance

#77 penyesuaian env dan kelola tambahan cookie
  README.md
  src_ui/quasar.conf.js
  src_ui/src/store/kegiatan/actions.js
  src_ui/src/store/otentikasi/actions.js
Labels: maintenance

#78 kelola lanjut state management
  src_ui/src/components/MenuSettings/MenuSettings.js
  src_ui/src/components/MenuSettings/MenuSettings.vue
  src_ui/src/pages/Login/login.js
  src_ui/src/store/otentikasi/getters.js
  src_ui/src/store/otentikasi/mutations.js
  src_ui/src/store/otentikasi/state.js
Labels: maintenance

#79 Koreksi label dan versi
  src_ui/package.json
  src_ui/src/pages/Login/Login.vue
Labels: maintenance

#80 Modifikasi fungsi service status pengguna
  Cargo.lock
  Cargo.toml
  src/app/permissions/mod.rs
  src/pengguna/handlers/check_user.rs
  src/pengguna/models.rs
  src/pengguna/routes.rs
  src/pengguna/services/check_user.rs
  src/pengguna/services/login_user.rs
Labels: maintenance

#81 Menerapkan pagination awal
  README.md
  src/kegiatan/services.rs
  src_ui/package.json
  src_ui/quasar.conf.js
  src_ui/src/pages/Utama/Utama.vue
  src_ui/src/pages/Utama/utama.js
  src_ui/src/store/kegiatan/actions.js
  src_ui/src/store/kegiatan/mutations.js
Labels: maintenance

#82 interaksi memuat kegiatan lanjut
  src_ui/package.json
  src_ui/src/pages/Utama/Utama.vue
  src_ui/src/pages/Utama/utama.js
  src_ui/src/store/kegiatan/mutations.js
  src_ui/src/store/kegiatan/state.js
Labels: maintenance

#83 penambahan properti instansi pengguna dan penyesuaian fungsi
  Cargo.lock
  Cargo.toml
  src/pengguna/dto.rs
  src/pengguna/helpers.rs
  src/pengguna/models.rs
Labels: maintenance

#84 cek data diri berdasarkan token yang dimiliki
  Cargo.lock
  Cargo.toml
  src/pengguna/handlers/get_me.rs
  src/pengguna/handlers/mod.rs
  src/pengguna/routes.rs
  src/pengguna/services/get_me.rs
  src/pengguna/services/mod.rs
Labels: maintenance

#85 pengkondisian layout pengaturan sesuai token
  src_ui/package.json
  src_ui/src/layouts/MainLayout/MainLayout.js
  src_ui/src/layouts/MainLayout/MainLayout.vue
Labels: maintenance

#86 modifikasi lanjut fungsi dan template profil
  src_ui/src/pages/Profil.vue
  src_ui/src/pages/Profil/Profil.vue
  src_ui/src/pages/Profil/profil.js
  src_ui/src/router/routes.js
Labels: maintenance
